export const metadata = {
    title: 'Sinar Asih Gallery',
    description: 'Generated by create next app',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <body className="overflow-hidden">{children}</body>
    )
  }
  