import Script from 'next/script'


export const metadata = {
  title: 'Register',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <body>
        {children}
      
 
        </body>
  )
}
