import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './utility/redux/provider'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sinar Asih Sumedang',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-base' >
      <body className={`${inter.className}`}>
        <Providers>
        {children}
        <Script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript" defer 
      ></Script>
        </Providers>
        </body>
    </html>
  )
}
